version: '3.6'
services: 
    postgres:
        image: postgres
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin123
        ports: 
            - "5432:5432"
            