version: '3.6'
services: 
    pokemon-db:
        image: postgres:12
        container_name: pokemon-db
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin123
        networks:
            - backend-network
    pokemon-api:
        image: renankuba/pokemon-api:1.0
        container_name: pokemon-api
        environment:
            DB_HOST: pokemon-db
            DB_PORT: 5432
            DB_USER: admin
            DB_PASS: admin123
        networks:
            - backend-network
        depends_on:
            - pokemon-db
        ports: 
            - "80:8080"
networks:
    backend-network:
        driver: bridge
        